CREATE DATABASE BarDG;

USE BarDG;

CREATE TABLE MENU(
Id INT PRIMARY KEY IDENTITY,
Item VARCHAR(255) NOT NULL,
Price DECIMAL(10,2)
);


CREATE TABLE SHEET_ORDER(
Id INT PRIMARY KEY IDENTITY,
IdOrder INT,
IdMenu INT FOREIGN KEY REFERENCES MENU(Id), 
Amount INT NOT NULL,
Discount DECIMAL DEFAULT 0
);

